//for authenticatiob and authorization
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";

//for category resources
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

// for user resources
export const CREATE_USER = "CREATE_USER";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";

// for city resources
export const CREATE_CITY = "CREATE_CITY";
export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CITY = "FETCH_CITY";
export const DELETE_CITY = "DELETE_CITY";
export const EDIT_CITY = "EDIT_CITY";

// for vendor resources
export const CREATE_VENDOR = "CREATE_VENDOR";
export const FETCH_VENDORS = "FETCH_VENDORS";
export const FETCH_VENDOR = "FETCH_VENDOR";
export const DELETE_VENDOR = "DELETE_VENDOR";
export const EDIT_VENDOR = "EDIT_VENDOR";

// for product resources
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// for policy resources
export const CREATE_POLICY = "CREATE_POLICY";
export const FETCH_POLICIES = "FETCH_POLICIES";
export const FETCH_POLICY = "FETCH_POLICY";
export const DELETE_POLICY = "DELETE_POLICY";
export const EDIT_POLICY = "EDIT_POLICY";

// for orders resources
export const CREATE_ORDER = "CREATE_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ASSIGNED_ORDERS = "FETCH_ASSIGNED_ORDERS";
export const FETCH_ASSIGNED_ORDER = "FETCH_ASSIGNED_ORDER";
export const DELETE_ASSIGNED_ORDER = "DELETE_ASSIGNED_ORDER";
export const EDIT_ASSIGNED_ORDER = "EDIT_ASSIGNED_ORDER";
export const CREATE_ASSIGNED_ORDER = "CREATE_ASSIGNED_ORDER";
export const FETCH_ONTRANSIT_ORDERS = "FETCH_ONTRANSIT_ORDERS";
export const FETCH_ONTRANSIT_ORDER = "FETCH_ONTRANSIT_ORDER";
export const EDIT_ONTRANSIT_ORDER = "FETCH_ONTRANSIT_ORDER";
export const DELETE_ONTRANSIT_ORDER = "FETCH_ONTRANSIT_ORDER";
export const CREATE_ONTRANSIT_ORDER = "CREATE_ONTRANSIT_ORDER";
export const FETCH_ORDER = "FETCH_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";

export const FETCH_COMPLETED_ORDERS = "FETCH_COMPLETED_ORDERS";
export const FETCH_COMPLETED_ORDER = "FETCH_COMPLETED_ORDER";
export const EDIT_COMPLETED_ORDER = "FETCH_COMPLETED_ORDER";
export const DELETE_COMPLETED_ORDER = "FETCH_COMPLETED_ORDER";
export const CREATE_COMPLETED_ORDER = "CREATE_COMP[LETED_ORDER";

// for payments resources
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const FETCH_PAYMENTS = "FETCH_PAYMENTS";
export const FETCH_PAYMENT = "FETCH_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";
export const EDIT_PAYMENT = "EDIT_PAYMENT";
export const BOOK_PAYMENT = "BOOK_PAYMENT";

// for remittance resources
export const PROCESS_REMITTANCE = "PROCESS_REMITTANCE";
export const FETCH_REMITTANCES = "FETCH_REMITTANCES";
export const FETCH_REMITTANCE = "FETCH_REMITTANCE";
export const DELETE_REMITTANCE = "DELETE_REMITTANCE";
export const EDIT_REMITTANCE = "EDIT_REMITTANCE";

// for countries resources
export const CREATE_COUNTRY = "CREATE_COUNTRY";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const DELETE_COUNTRY = "DELETE_COUNTRY";
export const EDIT_COUNTRY = "EDIT_COUNTRY";

// for state resources
export const CREATE_STATE = "CREATE_STATE";
export const FETCH_STATES = "FETCH_STATES";
export const FETCH_STATE = "FETCH_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const EDIT_STATE = "EDIT_STATE";

// for currency resources
export const CREATE_CURRENCY = "CREATE_CURRENCY";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const FETCH_CURRENCY = "FETCH_CURRENCY";
export const DELETE_CURRENCY = "DELETE_CURRENCY";
export const EDIT_CURRENCY = "EDIT_CURRENCY";

// for cluster resources
export const CREATE_CLUSTER = "CREATE_CLUSTER";
export const FETCH_CLUSTERS = "FETCH_CLUSTERS";
export const FETCH_CLUSTER = "FETCH_CLUSTER";
export const DELETE_CLUSTER = "DELETE_CLUSTER";
export const EDIT_CLUSTER = "EDIT_CLUSTER";

// for pending trips resources
export const CREATE_TRIP = "CREATE_TRIP";
export const FETCH_TRIPS = "FETCH_TRIPS";
export const FETCH_TRIP = "FETCH_TRIP";
export const DELETE_TRIP = "DELETE_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";

// for ontransit trips resources
export const CREATE_ONTRANSIT_TRIP = "CREATE_ONTRANSIT_TRIP";
export const FETCH_ONTRANSIT_TRIPS = "FETCH_ONTRANSIT_TRIPS";
export const FETCH_ONTRANSIT_TRIP = "FETCH_ONTRANSIT_TRIP";
export const DELETE_ONTRANSIT_TRIP = "DELETE_ONTRANSIT_TRIP";
export const EDIT_ONTRANSIT_TRIP = "EDIT_ONTRANSIT_TRIP";

// for fullfilled trips resources
export const CREATE_FULLFILLED_TRIP = "CREATE_FULLFILLED_TRIP";
export const FETCH_FULLFILLED_TRIPS = "FETCH_FULLFILLED_TRIPS";
export const FETCH_FULLFILLED_TRIP = "FETCH_FULLFILLED_TRIP";
export const DELETE_FULLFILLED_TRIP = "DELETE_FULLFILLED_TRIP";
export const EDIT_FULLFILLED_TRIP = "EDIT_FULLFILLED_TRIP";

// for completed payment resources
export const CREATE_FULLFILLED_PAYMENT = "CREATE_FULLFILLED_PAYMENT";
export const FETCH_FULLFILLED_PAYMENTS = "FETCH_FULLFILLED_PAYMENTS";
export const FETCH_FULLFILLED_PAYMENT = "FETCH_FULLFILLED_PAYMENT";
export const DELETE_FULLFILLED_PAYMENT = "DELETE_FULLFILLED_PAYMENT";
export const EDIT_FULLFILLED_PAYMENT = "EDIT_FULLFILLED_PAYMENT";

// for partial payment resources
export const CREATE_PARTIAL_PAYMENT = "CREATE_PARTIAL_PAYMENT";
export const FETCH_PARTIAL_PAYMENTS = "FETCH_PARTIAL_PAYMENTS";
export const FETCH_PARTIAL_PAYMENT = "FETCH_PARTIAL_PAYMENT";
export const DELETE_PARTIAL_PAYMENT = "DELETE_PARTIAL_PAYMENT";
export const EDIT_PARTIAL_PAYMENT = "EDIT_PARTIAL_PAYMENT";

// for partial remittance resources
export const PROCESS_PARTIAL_REMITTANCE = "PROCESS_PARTIAL_REMITTANCE";
export const FETCH_PARTIAL_REMITTANCES = "FETCH_PARTIAL_REMITTANCES";
export const FETCH_PARTIAL_REMITTANCE = "FETCH_PARTIAL_REMITTANCE";
export const DELETE_PARTIAL_REMITTANCE = "DELETE_PARTIAL_REMITTANCE";
export const EDIT_PARTIAL_REMITTANCE = "EDIT_PARTIAL_REMITTANCE";

// for complete remittance resources
export const PROCESS_COMPLETE_REMITTANCE = "PROCESS_COMPLETE_REMITTANCE";
export const FETCH_COMPLETE_REMITTANCES = "FETCH_COMPLETE_REMITTANCES";
export const FETCH_COMPLETE_REMITTANCE = "FETCH_COMPLETE_REMITTANCE";
export const DELETE_COMPLETE_REMITTANCE = "DELETE_COMPLETE_REMITTANCE";
export const EDIT_COMPLETE_REMITTANCE = "EDIT_COMPLETE_REMITTANCE";

// for related products
export const CREATE_RELATEDPRODUCT = "CREATE_RELATEDPRODUCT";
export const FETCH_RELATEDPRODUCTS = "FETCH_RELATEDPRODUCTS";
export const FETCH_RELATEDPRODUCT = "FETCH_RELATEDPRODUCT";
export const DELETE_RELATEDPRODUCT = "DELETE_RELATEDPRODUCT";
export const EDIT_RELATEDPRODUCT = "EDIT_RELATEDPRODUCT";

// for products on sale
export const CREATE_PRODUCTONSALE = "CREATE_PRODUCTONSALE";
export const FETCH_PRODUCTONSSALE = "FETCH_PRODUCTONSSALE";
export const FETCH_PRODUCTONSALE = "FETCH_PRODUCTONSALE";
export const DELETE_PRODUCTONSALE = "DELETE_PRODUCTONSALE";
export const EDIT_PRODUCTONSALE = "EDIT_PRODUCTONSALE";

//  orders for delivery action creators
export const FETCH_ORDERSFORDELIVERY = "FETCH_ORDERSFORDELIVERY";
export const FETCH_ORDERFORDELIVERY = "FETCH_ORDERFORDELIVERY";
export const DELETE_ORDERFORDELIVERY = "DELETE_ORDERFORDELIVERY";
export const EDIT_ORDERFORDELIVERY = "EDIT_ORDERFORDELIVERY";

//  rejected orders action creators
export const FETCH_REJECTEDORDERS = "FETCH_REJECTEDORDERS";
export const FETCH_REJECTEDORDER = "FETCH_REJECTEDORDER";
export const DELETE_REJECTEDORDER = "DELETE_REJECTEDORDER";
export const EDIT_REJECTEDORDER = "EDIT_REJECTEDORDER";

//  logistics Partner action creators
export const CREATE_LOGISTICSPARTNER = "CREATE_LOGISTICSPARTNER";
export const FETCH_LOGISTICSPARTNERS = "FETCH_LOGISTICSPARTNERS";
export const FETCH_LOGISTICSPARTNER = "FETCH_LOGISTICSPARTNER";
export const DELETE_LOGISTICSPARTNER = "DELETE_LOGISTICSPARTNER";
export const EDIT_LOGISTICSPARTNER = "EDIT_LOGISTICSPARTNER";

//  delivery action creators
export const CREATE_DELIVERY = "CREATE_DELIVERY";
export const FETCH_DELIVERIES = "FETCH_DELIVERIES";
export const FETCH_DELIVERY = "FETCH_DELIVERY";
export const DELETE_DELIVERY = "DELETE_DELIVERY";
export const EDIT_DELIVERY = "EDIT_DELIVERY";

//  ontransit delivery action creators
export const CREATE_ONTRANSITDELIVERY = "CREATE_ONTRANSITDELIVERY";
export const FETCH_ONTRANSITDELIVERIES = "FETCH_ONTRANSITDELIVERIES";
export const FETCH_ONTRANSITDELIVERY = "FETCH_ONTRANSITDELIVERY";
export const DELETE_ONTRANSITDELIVERY = "DELETE_ONTRANSITDELIVERY";
export const EDIT_ONTRANSITDELIVERY = "EDIT_ONTRANSITDELIVERY";

//  completed delivery action creators
export const CREATE_COMPLETEDDELIVERY = "CREATE_COMPLETEDDELIVERY";
export const FETCH_COMPLETEDDELIVERIES = "FETCH_COMPLETEDDELIVERIES";
export const FETCH_COMPLETEDDELIVERY = "FETCH_COMPLETEDDELIVERY";
export const DELETE_COMPLETEDDELIVERY = "DELETE_COMPLETEDDELIVERY";
export const EDIT_COMPLETEDDELIVERY = "EDIT_COMPLETEDDELIVERY";

//  return delivery action creators
export const CREATE_RETURNDELIVERY = "CREATE_RETURNDELIVERY";
export const FETCH_RETURNDELIVERIES = "FETCH_RETURNDELIVERIES";
export const FETCH_RETURNDELIVERY = "FETCH_RETURNDELIVERY";
export const DELETE_RETURNDELIVERY = "DELETE_RETURNDELIVERY";
export const EDIT_RETURNDELIVERY = "EDIT_RETURNDELIVERY";
